import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ligonier Trivia Game</title>
        <meta name="description" content="Ligonier trivia game generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold">
        Welcome to the Trivia Challenge
      </h1>
      <p>
        You will be presented with 10 true or false questions. Can you score 100%?
      </p>
      <Link href="/quiz" passHref>
        <button
          type="button"
          className="inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none"
        >
          BEGIN
        </button>
      </Link>
    </div>
  )
}
