import Head from 'next/head'
import Quiz from '../components/Quiz'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Ligonier Trivia Game</title>
                <meta name="description" content="Ligonier trivia game generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Quiz />
        </div>
    )
}
